sudo: false
language: node_js
services:
node_js:
  - 0.10
  - 0.12
before_script:
  - npm install -d
branches:
  only:
    - master
script:
  - npm test
addons:
  apt:
    packages:
      - libzmq3-dev
